define([], function() {
  return {
    "PropertyPaneDescription": "Write 1-3 sentences describing the functionality of this component.",
    "TitleFieldLabel": "Card title",
    "Title": "Adaptive Card Extension",
    "SubTitle": "Quick view",
    "PrimaryText": "Book your desk or check-in/out",
    "Description": "SafeDesk365 Adaptive Card Extension",
    "QuickViewButton": "Quick view",
    "RefreshQuickViewButton": "Refresh",
    "BookDeskButton": "Book",
    "HereIsYourDesk": "Here is your free desk:",
    "DeskCode": "Desk code:",
    "DeskDescription": "Description:",
    "DeskCoffeeMachine": "Coffee machine:",
    "BookDeskAction": "Book!",
    "BookingConfirmed": "Congrats! Your booking is now registered with ID: ",
    "BookingDone": "Booking done!",
    "DoneAction": "Done!",
    "BookingChooseFlow": "Choose location, date, time slot, and your desk selection flow:",
    "BookingLocationLabel": "Location",
    "BookingLocationRequired": "Location is required",
    "BookingLocationPlaceholder": "Select location",
    "BookingDateLabel": "Date",
    "BookingDateRequired": "Date is required",
    "BookingTimeSlotLabel": "Time slot",
    "BookingTimeSlotRequired": "Time slot is required",
    "BookingTimeSlotPlaceholder": "Select time slot",
    "BookingTimeSlotMorning": "Morning",
    "BookingTimeSlotAfternoon": "Afternoon",
    "BookingFreeDesk": "Free Desk",
    "BookingSpecificDesk": "Specific Desk",
    "ChooseDesk": "Choose your desk:",
    "ChooseDeskPlaceholder": "Select desk",
    "ChooseDeskRequired": "Desk is required",
    "CheckInButton": "Check-in",
    "CheckOutButton": "Check-out",
    "BookTitle": "Book a Desk",
    "CheckInTitle": "Check-in a Desk",
    "CheckOutTitle": "Check-out a Desk",
    "SelectBookingCheckIn": "Select the booking to check-in",
    "SelectBookingCheckOut": "Select the booking to check-out",
    "BookingsListLocationColumn": "LOCATION",
    "BookingsListDeskColumn": "DESK",
    "BookingsListTimeSlotColumn": "TIME SLOT",
    "BookingsListActionColumn": "ACTION",
    "CheckIn": "Check-in!",
    "CheckOut": "Check-out!",
  }
});